# Declarative offline PKI (air/v0.1/pki.org), generated by the Rust
# kubenyx-pki tool: the entire PKI — CAs, leaves, SA keypair, kubeconfigs —
# in one ~5ms process on the boot critical path. No CA daemon, no network
# issuance — Nix is the trust channel. Fingerprint files gate regeneration;
# leaves renew inside the renewal window at every activation.
{
  config,
  lib,
  pkgs,
  ...
}:
let
  cfg = config.kubenyx;
  pki = cfg.internal.pkiDir;
  kc = cfg.internal.kubeconfigDir;

  thisNode = cfg.nodes.${cfg.nodeName} or {
    address = null;
    index = 0;
  };
  kubenyxPki = lib.getExe' cfg.internal.tools "kubenyx-pki";

  commonArgs = [
    kubenyxPki
    "--pki-dir"
    pki
    "--kubeconfig-dir"
    kc
    "--node-name"
    cfg.nodeName
    "--api-url"
    cfg.internal.apiserverUrl
  ];

  serverArgs =
    commonArgs
    ++ [
      "--mode"
      "server"
      "--cluster-domain"
      cfg.network.clusterDomain
      "--service-ip"
      cfg.internal.apiserverServiceIp
      "--leaf-days"
      (toString cfg.pki.leafValidityDays)
      "--renew-days"
      (toString cfg.pki.renewBeforeDays)
    ]
    ++ lib.optionals (thisNode.address != null) [
      "--node-address"
      thisNode.address
    ]
    ++ lib.concatMap (s: [
      "--extra-san"
      s
    ]) cfg.pki.extraApiserverSANs
    ++ lib.concatMap (
      n:
      let
        a = cfg.nodes.${n}.address;
      in
      [
        "--node"
        "${n}=${if a == null then "" else a}"
      ]
    ) (lib.attrNames cfg.nodes)
    ++ lib.optional (cfg.datastore.backend == "etcd") "--etcd";

  agentArgs = commonArgs ++ [
    "--mode"
    "agent"
  ];
in
{
  options.kubenyx.pki = {
    leafValidityDays = lib.mkOption {
      type = lib.types.ints.positive;
      default = 365;
      description = "Validity of leaf certificates.";
    };
    renewBeforeDays = lib.mkOption {
      type = lib.types.ints.positive;
      default = 30;
      description = "Regenerate leaves that expire within this window (checked every activation).";
    };
    extraApiserverSANs = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [ ];
      example = [
        "DNS:k8s.example.com"
        "IP:192.0.2.10"
      ];
      description = "Additional subjectAltName entries (DNS:/IP: prefixed) for the apiserver serving certificate.";
    };
  };

  config = lib.mkIf cfg.enable {
    assertions = [
      {
        assertion = lib.all (
          s: lib.hasPrefix "DNS:" s || lib.hasPrefix "IP:" s
        ) cfg.pki.extraApiserverSANs;
        message = "kubenyx: pki.extraApiserverSANs entries must be prefixed DNS: or IP:";
      }
    ];

    systemd.services.kubenyx-pki = {
      description =
        if cfg.role == "server" then "Kubenyx PKI generation" else "Kubenyx PKI (agent material)";
      wantedBy = [ "kubenyx.target" ];
      # network-online is only needed for node-IP autodetection: with a
      # declared address the PKI can run the moment the filesystem is up,
      # pulling the whole control-plane chain earlier in the boot.
      after = [
        "local-fs.target"
      ] ++ lib.optional (cfg.role == "server" && thisNode.address == null) "network-online.target";
      wants = lib.optional (cfg.role == "server" && thisNode.address == null) "network-online.target";
      serviceConfig = {
        Type = "oneshot";
        # Agents: RemainAfterExit=false so the path unit below can re-trigger
        # the renderer when credential material arrives or is re-shipped.
        RemainAfterExit = cfg.role == "server";
        TimeoutStartSec = 300;
        ExecStart = lib.escapeShellArgs (if cfg.role == "server" then serverArgs else agentArgs);
      };
    };

    # Agents: re-render kubeconfigs whenever the shipped credential
    # directory changes — first arrival and every renewal re-ship.
    systemd.paths.kubenyx-pki = lib.mkIf (cfg.role == "agent") {
      wantedBy = [ "multi-user.target" ];
      pathConfig = {
        PathModified = pki;
        Unit = "kubenyx-pki.service";
      };
    };
  };
}
